k3d-intall: add cleanup_on_success function to have a better way to clean leftover file with trap

diff --git a/scripts/k3d-install b/scripts/k3d-install
--- a/scripts/k3d-install
+++ b/scripts/k3d-install
@@ -157,8 +157,18 @@ EOF
 
    k3d cluster create --config "$yaml"
 
-   trap 'rm -f "$yaml"' EXIT INT
+   trap 'cleanup_on_success "$yaml"' EXIT
 
+}
+
+function cleanup_on_success() {
+   file_to_cleanup=$1
+   echo "Cleaning up temporary files..."
+   if [[ $? == 0 ]]; then
+      rm -f "$file_to_cleanup"
+   else
+      echo "Error occurred, not cleaning up $file_to_cleanup"
+   fi
 }
 
 function configure_k3d_cluster_istio() {
